### PR TITLE
create-volto-app reimplemented as Yeoman generator

### PR DESCRIPTION
**Pull request by tiberiuichim**
Benefits, some already implemented, some low-hanging fruit:

- biggest improvement: allow re-running a generator over an existing Volto project, to update the project files to latest template files from the generator. See screenshot for how this would look like. There's options like: image with inline options
- allows (future) unification of create-volto-app with volto-addon-cli, to be able to generate addons from the same package
- Easier maintainance of the create-volto-app package. The generator uses npm Package Registry to check the latest Volto release and uses that in the generated dependencies. It downloads the ``yarn.lock`` file from that Volto release
- It understands some command line options:

```
Usage:
  yo create-volto-app:app [<projectName>] [options]

Options:
  -h,   --help          # Print the generator's options and usage
        --skip-cache    # Do not remember prompt answers                                        Default: false
        --skip-install  # Do not automatically install dependencies                             Default: false
        --addon         # Addon loader string, like: some-volto-addon:loadExtra,loadOtherExtra
        --description   # Project description                                                   Default: A Volto-powered Plone frontend

Arguments:
  projectName    Type: String  Required: false
```

You can pass multiple ``--addon`` options and it will list them in the generated package.json. For the future, I'll enhance this to also allow a mrs.developer file to be passed as an option.

### CODE REVIEW

**Comment by tiberiuichim** [comment]
This is how you can test the package:

- run ``npm install --global yo``
- make a clone of this branch
- run "yarn && yarn link" inside it
- run ``yo create-volto-app bla --description "hello world" --addon one:x,y --addon two:z,t`` for an example of how it works
- edit the package.json to remove the bogus addons, but otherwise you can run "yarn" and "yarn start" in the generated project

**Comment by tiberiuichim** [comment]
To reviewers: be aware that this is a completely new package (instead of ``@plone/create-volto-app``, it needs to be ``generator-create-volto-app``. Timo suggested that we might use a different repo for that package. Maybe even include it in the Volto code source, although this will imply that we make Volto a multi-package repo. In any case, to me, ``generator-volto`` sounds nice, and it can include a ``yo volto:addon`` template, for Volto addon templates.

**Comment by tiberiuichim** [comment]
@jenkins-plone-org please run jobs

**Comment by nzambello** [comment]
I like this! Seems really interesting

**Comment by tiberiuichim** [comment]
Issues: gitignore file is not properly generated. package.json.tpl is not properly excluded.

**Review by nileshgulia1 — COMMENTED** [review]
@tiberiuichim This looks good already. Thanks 💯 
When developing this project long back in 2018 we came across this issue of not choosing yeoman. Maybe @sneridagh can throw some insights on it. 
Also I didn't able to find out how we are removing the dependency on volto-starter-kit repo from this?

But I like the concept of passing addons as a parameter when bootstrapping a volto project 👍 .

**Comment by sneridagh** [comment]
I love it! I really think we should continue explore this. 

@tiberiuichim can we make it a @plone repo? I already hacked around it a bit :)

**Comment by tiberiuichim** [comment]
@sneridagh Sure! Go ahead, fork it in plone.

**Comment by tiberiuichim** [comment]
@sneridagh Be aware that yeoman generators don't like namespaces (I think) if you want to run them with `yo`

**Comment by tiberiuichim** [comment]
Work continues in https://github.com/plone/generator-volto-app/

**Pull request closed without merging**
